# This is a config for E2B sandbox template.
# You can use template ID (qq9970v67sn2sucprd93) or template name (lovable-clone-nextjs-local) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-clone-nextjs-local") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-clone-nextjs-local") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-clone-nextjs-local')

team_id = "4cbf2aa9-99af-46e6-bdfd-c03d02e3daff"
start_cmd = "/home/user/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-clone-nextjs-local"
template_id = "qq9970v67sn2sucprd93"
